name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Build, Scan & Push
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build & Push Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # We tag it with the Commit SHA (Unique ID) AND 'latest'
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/gitops-demo-app:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/gitops-demo-app:latest

    # 4. The "Git Write Back" Step
    - name: Update Kubernetes Manifest
      env:
        # We use the PAT to get write access to the OTHER repo
        GITHUB_TOKEN: ${{ secrets.GITOPS_PAT }}
      run: |
        # Configure Git
        git config --global user.email "ci-bot@example.com"
        git config --global user.name "CI Bot"
        
        # Clone the Infrastructure Repo (Repo B)
        # REPLACE 'reddypolukarthikeya' WITH YOUR USERNAME BELOW
        git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/reddypolukarthikeya/gitops-infra.git
        
        cd gitops-infra
        
        # Use 'sed' to replace the image tag in the deployment file
        # It looks for "image: ... :something" and replaces "something" with the new ID
        sed -i 's|image: .*|image: karthikpreddy/gitops-demo-app:${{ github.sha }}|' infrastructure/demo-app/deployment.yaml
        
        # Check if anything changed
        if [[ -n $(git status -s) ]]; then
          git add .
          git commit -m "Auto-update image tag to ${{ github.sha }}"
          git push
        else
          echo "No changes needed"
        fi
