name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Build, Scan & Push
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Login to Docker Hub (Using the secrets you added)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Set up Docker Buildx (The builder engine)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 4. Build the Image (But don't push yet - we need to scan it first)
    - name: Build and Export to Local Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true  # This brings the image into the local runner
        tags: ${{ secrets.DOCKER_USERNAME }}/gitops-demo-app:${{ github.sha }}

    # 5. Scan with Trivy (The Security Guard)
    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/gitops-demo-app:${{ github.sha }}'
        format: 'table'
        exit-code: '1'          # Fail the build if vulnerabilities are found
        ignore-unfixed: true    # Ignore bugs that have no fix yet
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    # 6. Push to Docker Hub (Only happens if Step 5 passes)
    - name: Build and Push
      if: success()
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/gitops-demo-app:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/gitops-demo-app:latest
